---
- hosts: localhost

  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - brave-browser
        - 1password
        - warp
        - docker
        - tailscale
        - google-drive 

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'wget',
           'gh',
           'iproute2mac',
           'tmux',
           'neovim',
              ]
