---
- hosts: localhost

  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ghostty
        - brave-browser
        - orbstack
        - 1password
        - signal
        - notion
        

    - name: "Install homebrew packages"
      community.general.homebrew:
        name:
          [
            'wget',
            'iproute2mac',
            'tmux',
            'neovim',
            'zsh-autosuggestions',
            'zsh-syntax-highlighting',
            'fastfetch',
            'stow',
            'eza',
            'starship'
          ]

