---
- hosts: localhost

  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - warp
        - brave-browser
        - orbstack
        - 1password
        

    - name: "Install homebrew packages"
      community.general.homebrew:
        name:
          [
            'wget',
            'iproute2mac',
            'tmux',
            'neovim'
          ]

