---
- hosts: localhost

  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - warp
        - obsidian
        - visual-studio-code
        - docker
        - brave-browser
        - google-chrome
        - vivaldi
        - ledger-live
        - tailscale
        - 1password
        - google-cloud-sdk

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'wget',
           'mas',
           'gh',
           'awscli',
           'iproute2mac',
           'tmux',
           'fish',
  ]


