---
- hosts: localhost

  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - iterm2
        - warp
        - brave-browser
        - google-chrome
        - google-cloud-sdk
        - visual-studio-code
        - tailscale
        - telegram
        - signal
        - ledger-live
        - exodus
        - 1password
        - docker
        - balenaetcher
        - virtualbox

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'wget',
           'mas',
           'dockutil',
           'gh',
           'starship',
           'fish',
           'awscli',
  ]


